PREFIX era: <http://data.europa.eu/949/>

SELECT DISTINCT ?inCountry ?numTotalTracks ?numTracksWithLoadCapability ?numTracksWithoutLoadCapability
WHERE {
GRAPH <http://data.europa.eu/949/graph/rinf> {
{
SELECT DISTINCT ?inCountry (COUNT(DISTINCT ?track) AS ?numTotalTracks)
WHERE {
  ?track a era:Track .  
  ?sectionOfLine era:track ?track .
  ?sectionOfLine a era:SectionOfLine .
  ?sectionOfLine era:inCountry ?inCountry.
} 
}
{
SELECT DISTINCT ?inCountry (COUNT(DISTINCT ?track) AS ?numTracksWithLoadCapability)
WHERE {
  ?track a era:Track .  
  ?track era:trackLoadCapability ?loadCapability .
  ?sectionOfLine era:track ?track .
  ?sectionOfLine a era:SectionOfLine .
  ?sectionOfLine era:inCountry ?inCountry.
} 
}
FILTER (?numTotalTracks = ?numTracksWithLoadCapability)
BIND(0 AS ?numTracksWithoutLoadCapability)
}
}
