PREFIX era: <http://data.europa.eu/949/>

SELECT DISTINCT ?p ?inCountry ?numTotalSOLs ?numSOLsWithPropertyAsCoreParameter ?numSOLsWithoutPropertyAsCoreParameter
WHERE {
  GRAPH <${{NAMED_KG_RINF}}> {
  VALUES ?p {era:length}
{
SELECT DISTINCT ?inCountry (COUNT(DISTINCT ?sectionOfLine) AS ?numTotalSOLs)
WHERE {
  ?sectionOfLine a era:SectionOfLine .
  ?sectionOfLine era:inCountry ?inCountry
} 
} OPTIONAL
{
SELECT DISTINCT ?inCountry ?p (COUNT(DISTINCT ?sectionOfLine) AS ?numSOLsWithPropertyAsCoreParameter)
WHERE {
  VALUES ?p {era:length}
  ?sectionOfLine a era:SectionOfLine .
  ?sectionOfLine ?p ?propertyValue .
  ?sectionOfLine era:inCountry ?inCountry.
} 
} OPTIONAL
{
SELECT DISTINCT ?inCountry ?p (COUNT(DISTINCT ?sectionOfLine) AS ?numSOLsWithoutPropertyAsCoreParameter) 
WHERE {
  VALUES ?p {era:length}
  ?sectionOfLine a era:SectionOfLine .
  ?sectionOfLine era:inCountry ?inCountry.
  FILTER NOT EXISTS {?sectionOfLine ?p ?propertyValue . VALUES ?p {era:length}}
} 
}
}
} ORDER BY ?p ?inCountry 
