PREFIX era: <http://data.europa.eu/949/>

SELECT DISTINCT ?track ?tds ?p ?rinfIndex  
WHERE {
  GRAPH <${{NAMED_KG_RINF}}> {
  VALUES ?inCountry {<http://publications.europa.eu/resource/authority/country/ESP>} .
  VALUES ?p {era:trainDetectionSystemType}
  ?track a era:Track .  
  ?track era:trainDetectionSystem ?tds .
  ?sectionOfLine era:track ?track .
  ?sectionOfLine a era:SectionOfLine .
  ?sectionOfLine era:inCountry ?inCountry.
  GRAPH <${{NAMED_KG_ERA_VOCABULARY}}> {?p era:rinfIndex ?rinfIndex} .
  FILTER NOT EXISTS {?tds ?p ?propertyValue .}
  }
} ORDER BY ?track ?tds LIMIT 1000 
