PREFIX era: <http://data.europa.eu/949/>

SELECT DISTINCT ?track ?cls ?p #?rinfIndex  
WHERE {
  GRAPH <http://data.europa.eu/949/graph/rinf> {
  VALUES ?inCountry {<http://publications.europa.eu/resource/authority/country/ESP>} .
  VALUES ?p {era:energySupplySystem era:contactLineSystemType}
  ?track a era:Track .  
  ?track era:contactLineSystem ?cls .
  FILTER NOT EXISTS {?track era:notApplicable ?p}.
  ?sectionOfLine era:track ?track .
  ?sectionOfLine a era:SectionOfLine .
  ?sectionOfLine era:inCountry ?inCountry.
  GRAPH <http://data.europa.eu/949/graph/ontology> {?p era:rinfIndex ?rinfIndex} .
  FILTER NOT EXISTS {?cls ?p ?propertyValue .}
  }
} ORDER BY ?track ?cls LIMIT 1000 