PREFIX era: <http://data.europa.eu/949/>

SELECT DISTINCT ?entity ?p ?rinfIndex  
WHERE {
  GRAPH <${{NAMED_KG_RINF}}> {
  VALUES ?inCountry {<http://publications.europa.eu/resource/authority/country/ESP>} .
  VALUES ?p {era:lengthOfSiding era:minimumHorizontalRadius}
  ?entity a era:Siding .
  ?op a era:OperationalPoint .
  ?op era:siding ?entity .
  ?op era:inCountry ?inCountry .
  GRAPH <${{NAMED_KG_ERA_VOCABULARY}}> {?p era:rinfIndex ?rinfIndex} .
  FILTER NOT EXISTS {?entity ?p ?propertyValue}
  }
} ORDER BY ?entity LIMIT 1000 
