PREFIX era: <http://data.europa.eu/949/>
PREFIX era-dir: <http://data.europa.eu/949/concepts/track-running-directions/>
PREFIX era-op-types: <http://data.europa.eu/949/concepts/op-types/rinf/>

SELECT DISTINCT ?op ?uopid ?country WHERE {
    GRAPH <${{NAMED_KG_RINF}}> {
    # Main OP to be analyzed
    ?op era:inCountry ?country;
        era:uopid ?uopid .
         
# Condition: Operational point is not a border point
     FILTER NOT EXISTS {
     ?op era:opType era-op-types:90 } #border point
# Condition: There are no other SoLs reaching the OP
  FILTER NOT EXISTS {
        ?sol era:opEnd ?opCanonURI . ?op era:canonicalURI ?opCanonURI
    }
# Condition: There are no other SoLs leaving from the OP
  FILTER NOT EXISTS {
       ?sol era:opStart ?opCanonURI . ?op era:canonicalURI ?opCanonURI
}
}
}
ORDER BY ?op ?country
