PREFIX era: <http://data.europa.eu/949/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT DISTINCT ?id ?inCountry ?count
WHERE{
GRAPH <http://data.europa.eu/949/graph/rinf> {
{SELECT DISTINCT ?inCountry (COUNT(DISTINCT ?OP) AS ?count)
FROM <http://data.europa.eu/949/graph/rinf>
WHERE {
      ?OP a era:OperationalPoint.
      ?OP era:canonicalURI ?OP .
      ?OP era:inCountry ?inCountry.
}}
SERVICE <http://publications.europa.eu/webapi/rdf/sparql>{
      ?inCountry dc:identifier ?id
}
}
} 