PREFIX era: <http://data.europa.eu/949/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT *
FROM <${{NAMED_KG_RINF}}>
FROM <${{NAMED_KG_ERA_SKOS}}>
{

    ?sol a era:SectionOfLine. 
    ?sol era:opStart ?op_startCanonUri.
	?op_start era:canonicalURI ?op_startCanonUri.
    ?op_start era:opName ?op_startName .
    ?sol era:opEnd ?op_endCanonUri.
	?op_end era:canonicalURI ?op_endCanonUri.
    ?op_end era:opName ?op_endName .
    FILTER (regex(?op_startName,"Dendermonde")) .
    FILTER (regex(?op_endName,"Zele")).
    ?sol era:track ?track .
    ?track era:trackId ?trackId .
    ?track era:etcsLevel ?etcsLevel .
    ?etcsLevel era:etcsLevelType [skos:prefLabel ?etcsLevelType] .
    
    
}




