PREFIX era: <http://data.europa.eu/949/>

SELECT DISTINCT ?country ?p (COUNT(DISTINCT ?track) AS ?numberTracks)
WHERE {
GRAPH <${{NAMED_KG_RINF}}> {
  ?sectionOfLine a era:SectionOfLine .
  ?sectionOfLine era:inCountry ?country .
  ?sectionOfLine era:track ?track .
  ?track a era:Track .  
  ?track era:trainDetectionSystem ?tds .
  ?tds a era:TrainDetectionSystem .
  VALUES ?p {era:tsiCompliantCompositeBrakeBlocks era:tsiCompliantFerromagneticWheel era:tsiCompliantMaxImpedanceWheelset era:tsiCompliantMetalConstruction era:tsiCompliantMetalFreeSpace era:tsiCompliantRSTShuntImpedance era:tsiCompliantSandCharacteristics era:tsiCompliantSanding era:tsiCompliantShuntDevices } 
  ?tds ?p <http://data.europa.eu/949/concepts/tsi-compliances/rinf/20>
  }
}  ORDER BY ?country ?p
