PREFIX era: <http://data.europa.eu/949/> 
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT COUNT(DISTINCT ?x) AS ?count 
FROM <http://data.europa.eu/949/graph/prod/rinf>
WHERE {  
       ?x a era:OperationalPoint.
}