PREFIX era: <http://data.europa.eu/949/> 
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT DISTINCT ?inCountry (COUNT(DISTINCT ?track) AS ?count) 
FROM <http://data.europa.eu/949/graph/prod/rinf>
WHERE {  
       {?x a era:SectionOfLine} UNION {?x a era:OperationalPoint}.
       ?x era:track ?track .
       ?x era:inCountry ?inCountry.
} 